sudo: false
language: node_js

addons:
  firefox: "latest"

node_js:
  - 'node'
  - 'lts/*'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'

before_script:

  # Set up a virtual screen for Firefox.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
