sudo: false
language: node_js

addons:
  firefox: "latest"

node_js:
  - 'node'
  - '4.2'
  - '0.12'
  - '0.10'

before_script:

  # Set up a virtual screen for Firefox.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
